"""
Progress Tracker Agent Pydantic Models

Request/Response models specific to the Progress Tracker Agent.
"""

from typing import Optional, List, Dict
from pydantic import BaseModel, Field
from backend.shared.models import TopicMastery, LearningProgress


class MasteryRequest(BaseModel):
    """Request to update student mastery for a topic"""
    student_id: str = Field(..., description="Student identifier")
    topic: str = Field(..., description="Topic name")
    interaction_type: str = Field(..., description="Type of interaction: query, success, error, hint_request")
    success: bool = Field(default=True, description="Was the interaction successful?")
    score: Optional[float] = Field(None, description="Direct score percentage (0-100) to set for topic mastery")


class MasteryResponse(BaseModel):
    """Response containing student's mastery levels"""
    student_id: str
    overall_mastery: float = Field(..., ge=0.0, le=1.0, description="Overall mastery score")
    topic_mastery: List[TopicMastery] = Field(default_factory=list)
    struggling_topics: List[str] = Field(default_factory=list, description="Topics where student is struggling")
    next_recommended_topic: Optional[str] = Field(None, description="Recommended next topic to study")


class StruggleDetectionRequest(BaseModel):
    """Request to detect if student is struggling"""
    student_id: str = Field(..., description="Student identifier")
    recent_queries: List[str] = Field(..., description="Recent query texts")
    recent_errors: List[str] = Field(default_factory=list, description="Recent error messages")


class StruggleDetectionResponse(BaseModel):
    """Response indicating if student is struggling"""
    student_id: str
    is_struggling: bool
    confidence: float = Field(..., ge=0.0, le=1.0)
    struggle_indicators: List[str] = Field(default_factory=list, description="What indicates struggle")
    suggested_interventions: List[str] = Field(default_factory=list, description="Recommended actions")


class LearningInsight(BaseModel):
    """Personalized learning insight generated by Claude API"""
    student_id: str
    insight_type: str = Field(..., description="Type: strength, weakness, recommendation, milestone")
    title: str = Field(..., description="Brief title for the insight")
    description: str = Field(..., description="Detailed description")
    action_items: List[str] = Field(default_factory=list, description="Actionable next steps")
    generated_at: int = Field(..., description="Unix timestamp when generated")


class ProgressUpdate(BaseModel):
    """Progress update published to Kafka"""
    student_id: str
    topic: str
    old_mastery: float
    new_mastery: float
    interaction_count: int
    timestamp: int


class StudentProgressState(BaseModel):
    """Complete student progress state stored in Dapr"""
    student_id: str
    progress: LearningProgress
    total_queries: int = 0
    total_successful_queries: int = 0
    last_active_timestamp: int
    struggling_topics: List[str] = Field(default_factory=list)
