"""
Pydantic models for LearnFlow platform.

These models define the data structures used across all agents for:
- Student queries
- Agent responses
- Kafka message envelopes
- Health metrics
- Learning progress
"""

from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from uuid import uuid4


# ============================================================================
# Enums
# ============================================================================

class QueryStatus(str, Enum):
    """Status of a student query"""
    PENDING = "pending"
    ANALYZING = "analyzing"
    ROUTED = "routed"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    TIMEOUT = "timeout"


class IntentType(str, Enum):
    """Detected intent from Triage Agent"""
    CONCEPT = "concept"
    CODE_REVIEW = "code_review"
    DEBUG = "debug"
    EXERCISE = "exercise"
    PROGRESS = "progress"
    UNCLEAR = "unclear"


class AgentStatus(str, Enum):
    """Health status of an agent"""
    ACTIVE = "active"
    IDLE = "idle"
    DEGRADED = "degraded"
    ERROR = "error"


class LogLevel(str, Enum):
    """Log severity levels"""
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"
    SUCCESS = "SUCCESS"


# ============================================================================
# Core Models
# ============================================================================

class StudentQuery(BaseModel):
    """A question submitted by a student"""
    query_id: str = Field(default_factory=lambda: str(uuid4()))
    student_id: str
    query_text: str = Field(..., min_length=1, max_length=5000)
    code_snippet: Optional[str] = Field(None, max_length=10000)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    detected_intent: Optional[IntentType] = None
    routed_to_agent: Optional[str] = None
    confidence_score: Optional[float] = Field(None, ge=0.0, le=1.0)
    status: QueryStatus = QueryStatus.PENDING
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AgentResponse(BaseModel):
    """Response generated by a specialist agent"""
    response_id: str = Field(default_factory=lambda: str(uuid4()))
    query_id: str
    agent_type: str
    response_text: str = Field(..., min_length=1, max_length=20000)
    code_examples: List[str] = Field(default_factory=list)
    processing_time_ms: int = Field(..., ge=0)
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    claude_model: str = "claude-sonnet-3-5-20241022"
    token_count: int = Field(..., ge=0)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class KafkaMessageEnvelope(BaseModel):
    """Standard wrapper for all Kafka messages"""
    message_id: str = Field(default_factory=lambda: str(uuid4()))
    trace_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    event_type: str
    payload: Dict[str, Any]
    metadata: Dict[str, Any] = Field(default_factory=dict)
    schema_version: str = "1.0.0"


class AgentHealthMetrics(BaseModel):
    """Real-time monitoring data for agent status"""
    agent_name: str
    status: AgentStatus = AgentStatus.IDLE
    uptime_seconds: int = Field(default=0, ge=0)
    total_queries_processed: int = Field(default=0, ge=0)
    error_count: int = Field(default=0, ge=0)
    avg_response_time_ms: float = Field(default=0.0, ge=0.0)
    p95_response_time_ms: float = Field(default=0.0, ge=0.0)
    current_queue_depth: int = Field(default=0, ge=0)
    last_heartbeat: datetime = Field(default_factory=datetime.utcnow)
    version: str = "1.0.0"


class AgentLog(BaseModel):
    """Log entry for Hacker Terminal display"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    agent: str
    level: LogLevel
    message: str
    trace_id: Optional[str] = None


class TopicMastery(BaseModel):
    """Mastery level for a single curriculum topic"""
    topic_name: str
    mastery_percentage: float = Field(..., ge=0.0, le=100.0)
    exercises_completed: int = Field(default=0, ge=0)
    last_practiced: Optional[datetime] = None


class LearningProgress(BaseModel):
    """Progress tracking for a student"""
    student_id: str
    python_mastery_levels: List[TopicMastery] = Field(default_factory=list)
    overall_mastery: float = Field(default=0.0, ge=0.0, le=100.0)
    completed_exercises: int = Field(default=0, ge=0)
    topics_mastered: List[str] = Field(default_factory=list)
    strengths: List[str] = Field(default_factory=list)
    weaknesses: List[str] = Field(default_factory=list)
    learning_velocity: float = Field(default=0.0, ge=0.0)
    total_study_time_minutes: int = Field(default=0, ge=0)
    streak_days: int = Field(default=0, ge=0)
    last_updated: datetime = Field(default_factory=datetime.utcnow)


class StrugglingStudent(BaseModel):
    """Student detected as struggling (5+ failed runs)"""
    student_id: str
    student_name: Optional[str] = None
    failed_runs: int = Field(..., ge=5)
    current_topic: str
    last_activity: datetime
    struggling: bool = True
    intervention_message: Optional[str] = None


# ============================================================================
# Request/Response Models for API Endpoints
# ============================================================================

class QueryAnalysisRequest(BaseModel):
    """Request to Triage Agent for intent analysis"""
    query_id: str = Field(default_factory=lambda: str(uuid4()))
    student_id: str
    query_text: str = Field(..., min_length=1, max_length=5000)
    code_snippet: Optional[str] = Field(None, max_length=10000)
    context: Dict[str, Any] = Field(default_factory=dict)


class QueryAnalysisResponse(BaseModel):
    """Response from Triage Agent with routing decision"""
    query_id: str
    detected_intent: IntentType
    routed_to_agent: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    routing_reason: str
    estimated_complexity: str  # "simple" or "complex"
    processing_time_ms: int = Field(..., ge=0)


class HealthResponse(BaseModel):
    """Health check response"""
    status: str
    uptime_seconds: Optional[int] = None
    version: str = "1.0.0"


class ReadinessResponse(BaseModel):
    """Readiness check response"""
    ready: bool
    kafka_connected: bool
    dapr_connected: bool


# ============================================================================
# Helper Functions
# ============================================================================

def create_kafka_message(
    trace_id: str,
    event_type: str,
    payload: Dict[str, Any],
    metadata: Optional[Dict[str, Any]] = None
) -> KafkaMessageEnvelope:
    """Helper to create a standardized Kafka message"""
    return KafkaMessageEnvelope(
        trace_id=trace_id,
        event_type=event_type,
        payload=payload,
        metadata=metadata or {}
    )


def create_agent_log(
    agent: str,
    level: LogLevel,
    message: str,
    trace_id: Optional[str] = None
) -> AgentLog:
    """Helper to create an agent log entry"""
    return AgentLog(
        agent=agent,
        level=level,
        message=message,
        trace_id=trace_id
    )
